workflows:
  test-emulatorwtf:
    name: Patrol tests on emulator.wtf
    instance_type: mac_mini_m1
    max_build_duration: 30
    working_directory: packages/patrol/example
    environment:
      groups:
        - emulatorwtf
      flutter: 3.7.12

    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Preload Flutter artifacts
        script: |
          flutter precache

      - name: Set up Patrol CLI
        working_directory: packages/patrol_cli
        script: |
          dart pub global activate --source path . && patrol
      
      - name: Generate Gradle wrapper
        script: |
          flutter build apk --debug --flavor=does-not-exist || true
          
      - name: patrol build android
        script: |
          patrol build android
      
      - name: Run tests with emulator.wtf
        script: |
          ew-cli \
            --app build/app/outputs/apk/debug/app-debug.apk \
            --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --num-shards 3 \
            --use-orchestrator \
            --clear-package-data \
            --record-video \
            --timeout 10m \
            --environment-variables packageName="pl.leancode.patrol.example" \
            --outputs-dir test_artifacts \
            --outputs summary,merged_results_xml,coverage,pulled_dirs,results_xml,logcat,captured_video
        test_report: test_artifacts/*.xml

    artifacts:
        - test_artifacts
        - test_artifacts/*.xml

  test-ios-simulator:
    name: iOS simulator
    instance_type: mac_mini_m1
    max_build_duration: 30
    working_directory: packages/patrol/example
    environment:
      flutter: 3.7.12
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get

      - name: Preload Flutter artifacts
        script: flutter precache

      - name: Set up Patrol CLI
        working_directory: packages/patrol_cli
        script: dart pub global activate --source path . && patrol
      
      - name: Generate Gradle wrapper
        script: flutter build apk --debug --flavor=does-not-exist || true
        
      - name: Set up xcresultparser
        script: |
          brew tap a7ex/homebrew-formulae
          brew install xcresultparser

      - name: Run simulator
        script: xcrun simctl boot "iPhone 14 Pro Max"

      - name: Run tests on iPhone 14 Pro Max simulator
        script: |
          xcrun simctl io booted recordVideo --codec=h264 "video.mp4" &
          recordingpid="$!"
          
          xcrun simctl spawn booted log stream --type log --color none > all_simulator_logs.txt &
          logpid="$!"
          
          TESTS_EXIT_CODE=0
          patrol test --device="iPhone 14 Pro Max" || TESTS_EXIT_CODE=$?

          kill -SIGINT $recordingpid
          kill -SIGINT $logpid
          xcrun simctl shutdown all

          exit $TESTS_EXIT_CODE
        ignore_failure: true

      - name: Create test report
        script: |
          XCRESULT_PATH="$(find ~/Library/Developer/Xcode/DerivedData -name "*.xcresult" -type d)"
          echo "XCRESULT_PATH=$XCRESULT_PATH" >> $CM_ENV
          xcresultparser -o junit "$XCRESULT_PATH" > test_report.xml
        test_report: test_report.xml

    artifacts:
      - "all_simulator_logs.txt"
      - "video.mp4"
      - "${XCRESULT_PATH}"
      - "test_report.xml"

  test-android-device-ftb:
    name: Android device on FTL
    instance_type: mac_mini_m1
    max_build_duration: 30
    working_directory: packages/patrol/example
    environment:
      groups:
        - google_credentials # <-- (Includes GCLOUD_KEY_FILE, GOOGLE_CREDENTIALS)
      flutter: 3.7.12
      
    scripts:
      - name: Installl crcmod
        script: pip3 install -U crcmod
        
      - name: Get Flutter packages
        script: flutter packages pub get

      - name: Preload Flutter artifacts
        script: flutter precache

      - name: Set up Patrol CLI
        working_directory: packages/patrol_cli
        script: dart pub global activate --source path . && patrol
      
      - name: Generate Gradle wrapper
        script: flutter build apk --debug --flavor=does-not-exist || true
          
      - name: Set up FTL
        script: |
          echo $GCLOUD_KEY_FILE | base64 --decode > ./gcloud_key_file.json

          gcloud auth activate-service-account --key-file=gcloud_key_file.json

          gcloud --quiet config set project $FIREBASE_PROJECT
      
      - name: patrol build android
        script: |
          patrol build android \
            --exclude integration_test/permissions_location_test.dart \
            --exclude integration_test/service_airplane_mode_test.dart \
            --exclude integration_test/service_bluetooth_test.dart \
            --exclude integration_test/webview_hackernews_test.dart \
            --exclude integration_test/webview_leancode_test.dart \
            --exclude integration_test/webview_login_test.dart \
            --exclude integration_test/webview_stackoverflow_test.dart
      
      - name: Run Firebase Test Lab tests
        script: |
          set -euo pipefail

          RESULTS_DIR_NAME="$(date +"%Y-%m-%d_%H:%M:%S")"
          echo "RESULTS_DIR_NAME=$RESULTS_DIR_NAME" >> $CM_ENV

          exec gcloud firebase test android run \
            --type instrumentation \
            --app build/app/outputs/apk/debug/app-debug.apk \
            --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --device model=oriole,version=33,locale=en,orientation=portrait \
            --timeout 10m \
            --results-bucket="patrol_runs" \
            --results-dir="$RESULTS_DIR_NAME" \
            --use-orchestrator \
            --environment-variables clearPackageData=true,packageName="pl.leancode.patrol.example"
        ignore_failure: true

      - name: Get test outputs from GCS and create test report
        script: |
          mkdir "test_outputs"
          gsutil -m cp -r "gs://patrol_runs/${RESULTS_DIR_NAME}/oriole-33-en-portrait/*" "test_outputs"
        test_report: test_outputs/*.xml
          
    artifacts:
      - test_outputs

  test-ios-device-ftb:
    name: iOS device on FTL
    instance_type: mac_mini_m1
    max_build_duration: 30
    working_directory: packages/patrol/example
    environment:
      flutter: 3.7.12
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
        - gcloud_credentials
      vars:
        FIREBASE_PROJECT: "flutter-integration-tests"
        BUNDLE_ID: "io.codemagic.ftlflutter"
        TEST_BUNDLE_ID: "io.codemagic.ftlflutter.uitests.xctrunner"
    scripts:
      - name: Configure Firebase access
        script: |
          set -e
          echo $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS > ./gcloud_key_file.json          
          gcloud auth activate-service-account --key-file=gcloud_key_file.json
          gcloud --quiet config set project $FIREBASE_PROJECT

      - keychain initialize
      - app-store-connect fetch-signing-files ${BUNDLE_ID} --create
      - app-store-connect fetch-signing-files ${TEST_BUNDLE_ID} --create
      - keychain add-certificates
      - xcode-project use-profiles --code-signing-setup-verbose-logging

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Preload Flutter artifacts
        script: |
          flutter precache

      - name: Set up Patrol CLI
        working_directory: packages/patrol_cli
        script: |
          dart pub global activate --source path . && patrol
      
      - name: Generate Gradle wrapper
        script: |
          flutter build apk --debug --flavor=does-not-exist || true

      - name: patrol build ios \
        script: |
          patrol build ios \
            --exclude integration_test/android_app_test.dart \
            --exclude integration_test/service_airplane_mode_test.dart \
            --exclude integration_test/service_bluetooth_test.dart \
            --exclude integration_test/service_cellular_test.dart \
            --exclude integration_test/service_wifi_test.dart \
            --exclude integration_test/swipe_test.dart \
            --exclude integration_test/webview_leancode_test.dart \
            --exclude integration_test/webview_login_test.dart \
            --exclude integration_test/webview_stackoverflow_test.dart

      - name: Run tests in Firebase Test Lab
        script: |
          dev_target="16.2"
          product="build/ios_integ/Build/Products"
          rm -rf "$product"

          pushd "$product"
          zip -r ios_tests.zip Release-iphoneos "Runner_iphoneos$dev_target-arm64.xctestrun"
          popd

          RESULTS_DIR_NAME="$(date +"%Y-%m-%d_%H:%M:%S")"
          echo "RESULTS_DIR_NAME=$RESULTS_DIR_NAME" >> $CM_ENV

          exec gcloud firebase test ios run \
            --type xctest \
            --test "$product/ios_tests.zip" \
            --device model=iphone8,version="$dev_target",locale=en_US,orientation=portrait \
            --timeout 10m \
            --results-bucket=patrol_runs \
            --results-dir="$RESULTS_DIR_NAME" \
        ignore_failure: true

      - name: Get test outputs from Google Cloud Storage
        script: |
          mkdir "test_outputs"
          gsutil -m cp -r "gs://patrol_runs/${RESULTS_DIR_NAME}/oriole-33-en-portrait/*" "test_outputs"

    artifacts:
      - "test_outputs"
